"""Answer generation nodes — OWNER: M3.

Do not edit this file if you are not M3.
"""

from __future__ import annotations

from .state import AgentState


def answer_node(state: AgentState) -> dict:
    """Generate a final response using an LLM.

    *** MUST use a real LLM call — hardcoded strings will lose points. ***

    Ground the response in available context: query, tool_results, approval.
    Prompt constraint: use only facts present in the context; if a fact is missing,
    say it is missing rather than inventing it.

    CONTRACT:
    - MUST NOT return "route" (would corrupt metric_from_state's route comparison).
    - "final_answer" must be non-empty.
    - Event node name MUST be "answer".

    Return: {"final_answer": str, "events": [make_event("answer", ...)]}
    """
    raise NotImplementedError("TODO(M3): implement LLM-grounded answer generation")


def ask_clarification_node(state: AgentState) -> dict:
    """Ask for missing information instead of hallucinating.

    Generate ONE specific clarification question from the vague/incomplete query.
    If state["approval"] is a dict with approved is False, the question must reference
    the rejection reason and propose an alternative.

    CONTRACT:
    - MUST NOT return "route".
    - Set BOTH "pending_question" and "final_answer" (metric_from_state accepts either;
      setting both is the safe choice).
    - Event node name MUST be "clarify" (matches the graph node name).

    Return: {"pending_question": str, "final_answer": str, "events": [make_event("clarify", ...)]}
    """
    raise NotImplementedError("TODO(M3): implement clarification request")
