"""Tool / reliability nodes — OWNER: M4.

Do not edit this file if you are not M4.
"""

from __future__ import annotations

from .state import AgentState


def tool_node(state: AgentState) -> dict:
    """Execute a mock tool call, simulating transient failure on the error route.

    CONTRACT:
    - Read "attempt" from state (retry_or_fallback_node has ALREADY incremented it
      before this node runs on a retry pass).
    - If state["route"] == "error" and attempt < 2 -> result string MUST contain "ERROR".
      Otherwise -> mock success string that quotes a fact from the query (order id, etc.).
    - "tool_results" has an `add` reducer: return a LIST with just the new item,
      never the whole accumulated list.
    - MUST NOT return "route".
    - Event node name MUST be "tool".

    Traced behaviour this produces (verify at Gate 2):
      S05 max_attempts=3: retry(a=1) -> tool ERROR -> retry(a=2) -> tool OK -> answer
      S07 max_attempts=1: retry(a=1) -> 1 < 1 is False -> dead_letter immediately

    Return: {"tool_results": [result_string], "events": [make_event("tool", ...)]}
    """
    raise NotImplementedError("TODO(M4): implement mock tool with error simulation")


def evaluate_node(state: AgentState) -> dict:
    """Evaluate the latest tool result — the retry-loop gate.

    Bonus: LLM-as-judge for result quality, with the `"ERROR" in result` heuristic
    as the fallback layer.

    CONTRACT:
    - "evaluation_result" MUST be exactly "success" or "needs_retry" — routing.py
      compares against these literals.
    - MUST NOT return "route".
    - Event node name MUST be "evaluate".

    Return: {"evaluation_result": str, "events": [make_event("evaluate", ...)]}
    """
    raise NotImplementedError("TODO(M4): implement tool result evaluation")


def retry_or_fallback_node(state: AgentState) -> dict:
    """Record a retry attempt.

    CONTRACT:
    - Return attempt = state.get("attempt", 0) + 1.
    - Event node name MUST be exactly "retry" — metrics.py counts retries by
      `sum(1 for node in nodes if node == "retry")`. A different name = 0 retries.
    - Append one real message to "errors" (list reducer: return a 1-item list).
    - MUST NOT return "route".

    Return: {"attempt": int, "errors": [str], "events": [make_event("retry", ...)]}
    """
    raise NotImplementedError("TODO(M4): implement retry with attempt tracking")


def dead_letter_node(state: AgentState) -> dict:
    """Handle unresolvable failures after max retries exceeded.

    CONTRACT:
    - MUST NOT return "route" — S07's expected_route is "error", so overwriting
      route with "dead_letter" would fail the scenario.
    - "final_answer" explains N attempts were made and the request was escalated
      to a human queue.
    - Event node name MUST be "dead_letter".

    Return: {"final_answer": str, "events": [make_event("dead_letter", ...)]}
    """
    raise NotImplementedError("TODO(M4): implement dead letter handling")
