"""Classification node — OWNER: M2.

Do not edit this file if you are not M2.
"""

from __future__ import annotations

from .state import AgentState


def classify_node(state: AgentState) -> dict:
    """Classify the query into a route using an LLM.

    *** MUST use a real LLM call — keyword-only heuristics will lose up to 15 points. ***
    *** MUST use .with_structured_output() — regex/text parsing breaks hidden scenarios. ***

    CONTRACT:
    - This is the ONLY node allowed to return "route".
    - "route" MUST be one of exactly: "simple" | "tool" | "missing_info" | "risky" | "error"
      (Route.DEAD_LETTER / Route.DONE are NOT valid classifier outputs.)
    - "risk_level" is "high" for risky, "low" otherwise.
    - Priority guide for the prompt: risky > tool > missing_info > error > simple
    - NEVER branch on scenario_id or scenario wording. `grep -rn "scenario_id ==" src/`
      must return empty at Gate 3.
    - Wrap the LLM call in try/except: on failure return route "simple" + an entry in
      "errors" instead of raising. A raising node kills the whole graph run.

    Return: {"route": str, "risk_level": str, "errors": [...], "events": [make_event("classify", ...)]}
    """
    raise NotImplementedError("TODO(M2): implement LLM-based classification")
